version: '3'

services:
  server: &server
    build: './server'
    image: worldwolf-server
    container_name: worldwolf-server
    command: rails server
    ports:
      - '3200:3000'
    volumes:
      - './server:/app'
      - '/app/tmp'
    links:
      - database
      - redis
    tty: true # for debugging with binding.pry
    stdin_open: true # for debugging with binding.pry
    environment:
      REDIS_URL: 'redis://redis:6379'

  worker:
    <<: *server
    container_name: worldwolf-worker
    command: sidekiq -C config/sidekiq.yml
    ports: []

  client:
    build: './client'
    image: worldwolf-client
    container_name: worldwolf-client
    command: npm run start-dev
    ports:
      - '4200:4200'
    volumes:
      - './client:/app'
      - '/app/node_modules'

  database:
    image: postgres:10.3-alpine
    container_name: worldwolf-database
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - 'data:/var/lib/postgresql/data'

  redis:
    image: redis:3.2.11-alpine
    container_name: worldwolf-redis

volumes:
  data:
